const fs = require('fs');
const path = require('path');

const finalCars = [
  {"id":"toyota-century-2023-base","manufacturer":"トヨタ","model":"センチュリー","grade":"標準","bodyType":"セダン","price":19960000,"releaseDate":"2023-09","dimensions":{"length":5335,"width":1930,"height":1505,"wheelbase":3090,"weight":2370,"minTurningRadius":5.9,"groundClearance":130},"capacity":{"seating":5},"engine":{"type":"ハイブリッド","displacement":3456,"maxPower":"294kW(400PS)","maxTorque":"460N・m","transmission":"電気式無段変速機","driveSystem":"4WD"},"fuelEfficiency":{"wltcMode":13.3,"cityMode":11.9,"suburbanMode":13.7,"highwayMode":14.2,"ecoCarTax":false},"safety":{"collisionMitigationBrake":true,"falseStartSuppression":true,"laneDepartureWarning":true,"laneKeepingAssist":true,"adaptiveCruiseControl":true,"blindSpotMonitor":true,"camera360":true,"parkingAssist":true,"airbags":12},"comfort":{"navigation":true,"etc":true,"backCamera":true,"powerSeat":true,"seatHeater":true,"steeringHeater":true,"autoAircon":true,"ledHeadlight":true,"smartKey":true,"powerBackDoor":false,"handsFreeBackDoor":false,"sunroof":true},"images":{"exterior":["/images/placeholder-car.jpg"],"interior":["/images/placeholder-interior.jpg"]},"officialUrl":"https://toyota.jp/century/","description":"トヨタの最高級セダン。伝統と革新が融合した日本の誇り。"},
  
  {"id":"nissan-gt-r-2023-pure","manufacturer":"日産","model":"GT-R","grade":"Pure","bodyType":"スポーツカー","price":13389800,"releaseDate":"2023-01","dimensions":{"length":4710,"width":1895,"height":1370,"wheelbase":2780,"weight":1770,"minTurningRadius":5.7,"groundClearance":110},"capacity":{"seating":4},"engine":{"type":"ガソリン","displacement":3799,"maxPower":"419kW(570PS)","maxTorque":"637N・m","transmission":"DCT","driveSystem":"4WD"},"fuelEfficiency":{"wltcMode":7.8,"cityMode":5.6,"suburbanMode":7.7,"highwayMode":9.7,"ecoCarTax":false},"safety":{"collisionMitigationBrake":true,"falseStartSuppression":false,"laneDepartureWarning":false,"laneKeepingAssist":false,"adaptiveCruiseControl":false,"blindSpotMonitor":false,"camera360":false,"parkingAssist":false,"airbags":6},"comfort":{"navigation":true,"etc":false,"backCamera":true,"powerSeat":false,"seatHeater":false,"steeringHeater":false,"autoAircon":true,"ledHeadlight":true,"smartKey":true,"powerBackDoor":false,"handsFreeBackDoor":false,"sunroof":false},"images":{"exterior":["/images/placeholder-car.jpg"],"interior":["/images/placeholder-interior.jpg"]},"officialUrl":"https://www3.nissan.co.jp/vehicles/new/gt-r.html","description":"日本を代表するスーパースポーツカー。圧倒的なパフォーマンスを誇る。"},
  
  {"id":"honda-nsx-2023-base","manufacturer":"ホンダ","model":"NSX","grade":"標準","bodyType":"スポーツカー","price":24200000,"releaseDate":"2022-01","dimensions":{"length":4535,"width":1940,"height":1215,"wheelbase":2630,"weight":1800,"minTurningRadius":5.9,"groundClearance":110},"capacity":{"seating":2},"engine":{"type":"ハイブリッド","displacement":3493,"maxPower":"373kW(507PS)","maxTorque":"550N・m","transmission":"DCT","driveSystem":"4WD"},"fuelEfficiency":{"wltcMode":10.6,"cityMode":7.6,"suburbanMode":10.8,"highwayMode":12.3,"ecoCarTax":false},"safety":{"collisionMitigationBrake":true,"falseStartSuppression":false,"laneDepartureWarning":false,"laneKeepingAssist":false,"adaptiveCruiseControl":false,"blindSpotMonitor":false,"camera360":false,"parkingAssist":false,"airbags":6},"comfort":{"navigation":true,"etc":true,"backCamera":true,"powerSeat":true,"seatHeater":true,"steeringHeater":false,"autoAircon":true,"ledHeadlight":true,"smartKey":true,"powerBackDoor":false,"handsFreeBackDoor":false,"sunroof":false},"images":{"exterior":["/images/placeholder-car.jpg"],"interior":["/images/placeholder-interior.jpg"]},"officialUrl":"https://www.honda.co.jp/NSX/","description":"ホンダの技術の粋を集めたハイブリッドスーパースポーツ。"},
  
  {"id":"mazda-mx-30-2023-ev","manufacturer":"マツダ","model":"MX-30 EV","grade":"EV","bodyType":"SUV","price":4510000,"releaseDate":"2021-01","dimensions":{"length":4395,"width":1795,"height":1540,"wheelbase":2655,"weight":1660,"minTurningRadius":5.3,"groundClearance":160},"capacity":{"seating":5},"engine":{"type":"EV","maxPower":"107kW(145PS)","maxTorque":"271N・m","transmission":"AT","driveSystem":"FF"},"fuelEfficiency":{"cruisingRange":256,"ecoCarTax":true},"safety":{"collisionMitigationBrake":true,"falseStartSuppression":true,"laneDepartureWarning":true,"laneKeepingAssist":true,"adaptiveCruiseControl":true,"blindSpotMonitor":true,"camera360":true,"parkingAssist":true,"airbags":7},"comfort":{"navigation":true,"etc":true,"backCamera":true,"powerSeat":true,"seatHeater":true,"steeringHeater":true,"autoAircon":true,"ledHeadlight":true,"smartKey":true,"powerBackDoor":false,"handsFreeBackDoor":false,"sunroof":false},"images":{"exterior":["/images/placeholder-car.jpg"],"interior":["/images/placeholder-interior.jpg"]},"officialUrl":"https://www.mazda.co.jp/cars/mx-30/","description":"マツダ初の量産EV。個性的なデザインと環境性能を兼ね備える。"},
  
  {"id":"subaru-wrx-sti-2023-type-s","manufacturer":"スバル","model":"WRX STI","grade":"Type S","bodyType":"セダン","price":4620000,"releaseDate":"2021-11","dimensions":{"length":4595,"width":1795,"height":1475,"wheelbase":2650,"weight":1500,"minTurningRadius":5.6,"groundClearance":130},"capacity":{"seating":5},"engine":{"type":"ガソリン","displacement":1998,"maxPower":"205kW(279PS)","maxTorque":"375N・m","transmission":"CVT","driveSystem":"4WD"},"fuelEfficiency":{"wltcMode":10.8,"cityMode":7.9,"suburbanMode":10.9,"highwayMode":12.9,"ecoCarTax":false},"safety":{"collisionMitigationBrake":true,"falseStartSuppression":true,"laneDepartureWarning":true,"laneKeepingAssist":true,"adaptiveCruiseControl":true,"blindSpotMonitor":true,"camera360":false,"parkingAssist":true,"airbags":7},"comfort":{"navigation":false,"etc":false,"backCamera":true,"powerSeat":false,"seatHeater":true,"steeringHeater":false,"autoAircon":true,"ledHeadlight":true,"smartKey":true,"powerBackDoor":false,"handsFreeBackDoor":false,"sunroof":false},"images":{"exterior":["/images/placeholder-car.jpg"],"interior":["/images/placeholder-interior.jpg"]},"officialUrl":"https://www.subaru.jp/wrx/","description":"スバルのスポーツセダン。AWD性能と走りの楽しさを追求。"}
];

// 既存データに追加
const carsPath = path.join(__dirname, '../data/cars.json');
const existingCars = JSON.parse(fs.readFileSync(carsPath, 'utf8'));
const allCars = [...existingCars, ...finalCars];

fs.writeFileSync(carsPath, JSON.stringify(allCars, null, 2));
console.log('Added ' + finalCars.length + ' final cars. Total: ' + allCars.length + ' cars');
